export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const TRACKS = [
  { id: 0, label: "DSA", sublabel: "College hours", color: "#A78BFA", bg: "rgba(167,139,250,0.13)", icon: "📚" },
  { id: 1, label: "Full Stack", sublabel: "6:00 – 8:00 PM", color: "#6EE7B7", bg: "rgba(110,231,183,0.13)", icon: "💻" },
  { id: 2, label: "SD / DevOps", sublabel: "8:00 – 10:00 PM", color: "#FCD34D", bg: "rgba(252,211,77,0.13)", icon: "🏗" },
];
export const RAW=[
[1,0,0,"Memory Model","Memory Model & Basics",2],[1,0,1,"Semantic HTML","Semantic Markup",2],[1,0,2,"Scalability Basics","Scalability Basics",2],
[1,1,0,"Two Pointers","Two Pointers",2],[1,1,1,"CSS Layout Mastery","Grid & Flexbox",2],[1,1,2,"CAP Theorem","CAP Theorem",2],
[1,2,0,"Sliding Window","Sliding Window",2],[1,2,1,"JS Fundamentals","Closures & Scope",2],[1,2,2,"Load Balancing","Load Balancing",2],
[1,3,0,"Hash Maps & Sets","HashMaps & Sets",2],[1,3,1,"Event Loop & Async","Event Loop & Async",2],[1,3,2,"CDN & Caching","CDN & Caching",2],
[1,4,0,"Prefix Sum & Intervals","Prefix Sum & Intervals",2],[1,4,1,"Functional JS","Functional JS",2],[1,4,2,"Linux Basics","Linux Basics",2],
[1,5,0,"Week 1 DSA Review","Week Review & Mock",2],[1,5,1,"JS OOP & Prototypes","OOP & Prototypes",2],[1,5,2,"Shell Scripting","Shell Scripting",2],
[2,0,0,"Singly LL Basics","Singly LL Basics",2],[2,0,1,"React Core Concepts","Core Concepts & JSX",2],[2,0,2,"DB Replication & Scaling","DB Replication",2],
[2,1,0,"Slow-Fast Pointers","Slow-Fast Pointers",2],[2,1,1,"React Hooks Deep Dive","Hooks Deep Dive",2],[2,1,2,"Sharding Strategies","Sharding Strategies",2],
[2,2,0,"Advanced LL Problems","Advanced LL Problems",2],[2,2,1,"Performance Hooks","Performance Hooks",2],[2,2,2,"Docker Fundamentals","Docker Fundamentals",2],
[2,3,0,"Monotonic Stack","Monotonic Stack",2],[2,3,1,"State Management","Context API & State",2],[2,3,2,"Dockerfile & Image Building","Dockerfile & Images",2],
[2,4,0,"Hard Stack Problems","Hard Stack Problems",2],[2,4,1,"Custom Hooks","Custom Hooks",2],[2,4,2,"Docker Compose","Docker Compose",2],
[2,5,0,"Queues & Deque","Queue & Deque",2],[2,5,1,"Mini Project: Task Manager","Mini Project",3],[2,5,2,"Containerize Your App","Containerize App",2],
[3,0,0,"Tree Traversals","Traversals",2],[3,0,1,"Next.js App Router","App Router",2],[3,0,2,"URL Shortener","URL Shortener",2],
[3,1,0,"Path & LCA Problems","Path & LCA",2],[3,1,1,"Server Components & Data Fetching","Server Components",2],[3,1,2,"Pastebin Design","Pastebin Design",2],
[3,2,0,"BST Operations","BST Operations",2],[3,2,1,"Server Actions & Mutations","Server Actions",2],[3,2,2,"GitHub Actions Basics","GitHub Actions",2],
[3,3,0,"Heap Fundamentals","Heap Fundamentals",2],[3,3,1,"Authentication with NextAuth","NextAuth",2],[3,3,2,"Build & Test Pipeline","Build & Test Pipeline",2],
[3,4,0,"Advanced Heap Problems","Advanced Heap",2],[3,4,1,"Performance & SEO","Performance & SEO",2],[3,4,2,"Deploy Pipeline","Deploy Pipeline",2],
[3,5,0,"Trie Data Structure","Trie Data Structure",2],[3,5,1,"TypeScript Fundamentals","TS Fundamentals",2],[3,5,2,"Review & Docker in CI","Docker in CI",2],
[4,0,0,"Graph Basics & BFS","BFS & Basics",2],[4,0,1,"Node.js Internals","Node Internals",2],[4,0,2,"Chat Application","Chat App",2],
[4,1,0,"DFS & Topological Sort","DFS & Topo Sort",2],[4,1,1,"Express.js Deep Dive","Express Deep Dive",2],[4,1,2,"Kubernetes Fundamentals","Kubernetes Basics",2],
[4,2,0,"Union-Find (DSU)","Union-Find",2],[4,2,1,"REST API Design & Build","REST API Build",2],[4,2,2,"kubectl & Workloads","kubectl & Workloads",2],
[4,3,0,"Shortest Path Algorithms","Dijkstra & SP",2],[4,3,1,"JWT Authentication","JWT Auth",2],[4,3,2,"K8s Networking & Config","K8s Networking",2],
[4,4,0,"MST & Advanced Graph","MST & Advanced",2],[4,4,1,"File Uploads & Email","File Upload & Email",2],[4,4,2,"Deploy App to K8s","Deploy to K8s",2],
[4,5,0,"Graph Review","Graph Review",2],[4,5,1,"Production-Grade API","Production API",3],[4,5,2,"Helm Basics","Helm Charts",2],
[5,0,0,"1D DP Patterns","1D DP Patterns",2],[5,0,1,"SQL Mastery","SQL Mastery",2],[5,0,2,"Notification System","Notification System",2],
[5,1,0,"String DP","String DP",2],[5,1,1,"PostgreSQL Deep Dive","PostgreSQL Deep Dive",2],[5,1,2,"Prometheus & Grafana","Prometheus & Grafana",2],
[5,2,0,"Knapsack Variants","Knapsack Variants",2],[5,2,1,"MongoDB Deep Dive","MongoDB",2],[5,2,2,"Structured Logging","Structured Logging",2],
[5,3,0,"2D & Grid DP","2D Grid DP",2],[5,3,1,"Redis Mastery","Redis Mastery",2],[5,3,2,"Distributed Tracing","Distributed Tracing",2],
[5,4,0,"Interval & State DP","Interval DP",2],[5,4,1,"DB Integration Layer","DB Integration",2],[5,4,2,"Alerting & SRE Concepts","Alerting & SRE",2],
[5,5,0,"DP Review & Patterns","DP Review",2],[5,5,1,"DB Project Refactor","DB Refactor Project",3],[5,5,2,"Observability Setup","Observability Setup",2],
[6,0,0,"Backtracking Fundamentals","Fundamentals",2],[6,0,1,"GraphQL Fundamentals","GraphQL Basics",2],[6,0,2,"Rate Limiter Design","Rate Limiter Design",2],
[6,1,0,"Hard Backtracking","Hard Problems",2],[6,1,1,"GraphQL Advanced","GraphQL Advanced",2],[6,1,2,"Terraform Basics","Terraform Basics",2],
[6,2,0,"Greedy Algorithms","Greedy Algorithms",2],[6,2,1,"Real-Time with Socket.io","Socket.io",2],[6,2,2,"Terraform Advanced","Terraform Advanced",2],
[6,3,0,"Hard Greedy Problems","Hard Greedy",2],[6,3,1,"Build Real-Time Features","Real-Time Features",2],[6,3,2,"Distributed Cache Design","Distributed Cache",2],
[6,4,0,"Advanced Binary Search","Advanced BS",2],[6,4,1,"BullMQ & Job Queues","BullMQ",2],[6,4,2,"Ansible Basics","Ansible",2],
[6,5,0,"Bit Tricks & DP","Bit Tricks",2],[6,5,1,"Integration Project","Integration Project",3],[6,5,2,"Provision Cloud with Terraform","Provision Cloud",2],
[7,0,0,"String Algorithms","KMP & Rabin-Karp",2],[7,0,1,"Microservices Architecture","Architecture",2],[7,0,2,"News Feed (Twitter/Instagram)","News Feed Design",2],
[7,1,0,"Segment Tree","Segment Tree",2],[7,1,1,"gRPC & Protobuf","gRPC & Protobuf",2],[7,1,2,"Typeahead / Search Autocomplete","Typeahead Design",2],
[7,2,0,"Fenwick Tree (BIT)","Fenwick Tree",2],[7,2,1,"Event-Driven with Kafka","Kafka Events",2],[7,2,2,"DevSecOps Pipeline","DevSecOps",2],
[7,3,0,"Hard Graph Problems","Hard Graph Problems",2],[7,3,1,"Service Mesh & Patterns","Service Mesh",2],[7,3,2,"Video Streaming (YouTube)","Video Streaming",2],
[7,4,0,"Competitive Practice","Codeforces Practice",2],[7,4,1,"Backend Testing Strategy","Backend Testing",2],[7,4,2,"API & Infrastructure Security","Infra Security",2],
[7,5,0,"DSA Review","DSA Review",2],[7,5,1,"E2E Testing with Playwright","E2E Playwright",2],[7,5,2,"Harden CI + K8s Security","Harden K8s",2],
[8,0,0,"Timed Mock 1","Timed Mock 1",2],[8,0,1,"Architecture Planning","Architecture Plan",2],[8,0,2,"Consensus: Raft & Paxos","Raft & Paxos",2],
[8,1,0,"Timed Mock 2","Timed Mock 2",2],[8,1,1,"Core: Auth + DB Setup","Auth + DB Core",3],[8,1,2,"Distributed Storage Deep Dive","Distributed Storage",2],
[8,2,0,"Timed Mock 3","Timed Mock 3",2],[8,2,1,"Core: Real-Time + File Upload","Real-Time + Upload",3],[8,2,2,"GitOps with ArgoCD","GitOps & ArgoCD",2],
[8,3,0,"Weakness Drill","Weakness Drill",2],[8,3,1,"Frontend: Dashboard & UI","Frontend Dashboard",3],[8,3,2,"SD Mock: Payment System","SD Mock: Payments",3],
[8,4,0,"Full 90-min Mock","90-min Full Mock",3],[8,4,1,"Testing & Polish","Testing & Polish",2],[8,4,2,"SD Mock: Google Docs","SD Mock: Google Docs",3],
[8,5,0,"Final DSA Review","Final DSA Review",3],[8,5,1,"Deploy to Production","Deploy to Production",3],[8,5,2,"SD Mock: WhatsApp","SD Mock: WhatsApp",3],
[9,0,0,"Hard Problems Session 1","Hard Problems #1",2],[9,0,1,"Web Performance Deep Dive","Web Vitals & Perf",2],[9,0,2,"Ride-Sharing (Uber Design)","Uber Design",2],
[9,1,0,"Hard Problems Session 2","Hard Problems #2",2],[9,1,1,"Advanced TypeScript","Advanced TypeScript",2],[9,1,2,"Web Search Engine Design","Search Engine Design",2],
[9,2,0,"Contest Simulation","Contest Simulation",2],[9,2,1,"TypeScript in Production","TS in Production",2],[9,2,2,"Resilience Testing","Chaos Engineering",2],
[9,3,0,"Speed & Accuracy Drill","Speed Drill",2],[9,3,1,"Clean Architecture","Clean Architecture",2],[9,3,2,"Object Storage (S3 Design)","Object Storage (S3)",2],
[9,4,0,"Hard Problems Session 3","Hard Problems #3",2],[9,4,1,"Monorepo with Turborepo","Turborepo Monorepo",2],[9,4,2,"Cloud Cost Management","Cloud Cost Optimization",2],
[9,5,0,"DSA Cheat Sheet","DSA Cheat Sheet",3],[9,5,1,"Refactor with Clean Arch","Clean Arch Refactor",2],[9,5,2,"Master SD Cheat Sheet","SD Cheat Sheet",3],
[10,0,0,"DSA Full Mock 1","DSA Full Mock 1",3],[10,0,1,"GitHub & Projects Polish","GitHub Polish",2],[10,0,2,"SD Mock: Twitter","SD Mock: Twitter",3],
[10,1,0,"DSA Full Mock 2","DSA Full Mock 2",3],[10,1,1,"Resume & LinkedIn","Resume & LinkedIn",2],[10,1,2,"SD Mock: WhatsApp (Retry)","SD Mock: WhatsApp",3],
[10,2,0,"Weak Area Final Drill","Weak Area Drill",2],[10,2,1,"Open Source Contribution","Open Source PR",3],[10,2,2,"DevOps Master Reference","DevOps Reference Doc",2],
[10,3,0,"DSA Speed Round","Speed Round",2],[10,3,1,"Full Stack Mock Interview","FS Mock Interview",3],[10,3,2,"SD Mock: Dropbox","SD Mock: Dropbox",3],
[10,4,0,"Grand Simulation","Grand Simulation",3],[10,4,1,"Behavioural & HR Prep","Behavioural Prep",2],[10,4,2,"SD Mock: YouTube","SD Mock: YouTube",3],
[10,5,0,"Plan Next 3 Months","Plan Next 3 Months",2],[10,5,1,"Deploy & Share Work","Deploy & Share Work",2],[10,5,2,"Write Your Learnings","Write Your Learnings",2],
];

export const RESOURCES = {
  "Arrays":["https://leetcode.com/tag/array/","https://www.youtube.com/results?search_query=arrays+dsa","https://neetcode.io/roadmap"],
  "Hashing":["https://leetcode.com/tag/hash-table/","https://www.youtube.com/results?search_query=hashing+dsa"],
  "Linked Lists":["https://leetcode.com/tag/linked-list/","https://visualgo.net/en/list"],
  "Stacks":["https://leetcode.com/tag/stack/","https://www.youtube.com/results?search_query=stack+problems"],
  "Queues":["https://leetcode.com/tag/queue/","https://visualgo.net/en/list"],
  "Binary Trees":["https://leetcode.com/tag/tree/","https://visualgo.net/en/bst"],
  "BST":["https://leetcode.com/tag/binary-search-tree/","https://visualgo.net/en/bst"],
  "Heaps":["https://leetcode.com/tag/heap-priority-queue/","https://visualgo.net/en/heap"],
  "Tries":["https://leetcode.com/tag/trie/","https://www.youtube.com/results?search_query=trie+data+structure"],
  "Graphs":["https://leetcode.com/tag/graph/","https://visualgo.net/en/dfsbfs","https://cp-algorithms.com/graph/"],
  "Dynamic Programming":["https://leetcode.com/tag/dynamic-programming/","https://atcoder.jp/contests/dp","https://neetcode.io/roadmap"],
  "Backtracking":["https://leetcode.com/tag/backtracking/","https://www.youtube.com/results?search_query=backtracking+algorithm"],
  "Greedy":["https://leetcode.com/tag/greedy/","https://cp-algorithms.com/"],
  "Binary Search":["https://leetcode.com/tag/binary-search/","https://www.youtube.com/results?search_query=binary+search+advanced"],
  "Bit Manipulation":["https://leetcode.com/tag/bit-manipulation/"],
  "String Algorithms":["https://leetcode.com/tag/string/","https://cp-algorithms.com/string/"],
  "Advanced DS":["https://cp-algorithms.com/data_structures/","https://cses.fi/problemset/"],
  "Competitive":["https://codeforces.com/","https://atcoder.jp/","https://leetcode.com/contest/"],
  "Mock Practice":["https://leetcode.com/contest/","https://www.pramp.com/"],
  "Final Mock":["https://leetcode.com/contest/","https://www.pramp.com/","https://interviewing.io/"],
  "HTML5":["https://developer.mozilla.org/en-US/docs/Web/HTML","https://web.dev/learn/html"],
  "CSS":["https://developer.mozilla.org/en-US/docs/Web/CSS","https://web.dev/learn/css","https://cssgridgarden.com/"],
  "JavaScript":["https://javascript.info/","https://developer.mozilla.org/en-US/docs/Web/JavaScript"],
  "React":["https://react.dev/","https://www.youtube.com/results?search_query=react+hooks+tutorial"],
  "Next.js":["https://nextjs.org/docs","https://nextjs.org/learn"],
  "TypeScript":["https://www.typescriptlang.org/docs/","https://typescript-exercises.github.io/"],
  "Node.js":["https://nodejs.org/en/docs/","https://expressjs.com/"],
  "Databases":["https://sqlbolt.com/","https://university.mongodb.com/","https://redis.io/docs/"],
  "GraphQL":["https://graphql.org/learn/","https://www.apollographql.com/docs/"],
  "WebSockets":["https://socket.io/docs/","https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API"],
  "Message Queues":["https://docs.bullmq.io/","https://www.rabbitmq.com/tutorials"],
  "Microservices":["https://microservices.io/","https://grpc.io/docs/"],
  "Testing":["https://jestjs.io/docs/","https://playwright.dev/docs/intro"],
  "Full Stack Project":["https://github.com/topics/fullstack","https://roadmap.sh/full-stack"],
  "Full Stack":["https://roadmap.sh/full-stack"],
  "Performance":["https://web.dev/performance/","https://pagespeed.web.dev/"],
  "Architecture":["https://blog.cleancoder.com/","https://turbo.build/repo/docs"],
  "Portfolio":["https://github.com/","https://www.linkedin.com/"],
  "Interview Prep":["https://www.pramp.com/","https://interviewing.io/"],
  "System Design":["https://github.com/donnemartin/system-design-primer","https://www.youtube.com/@gaborgyorfi/videos","https://bytebytego.com/"],
  "DevOps":["https://roadmap.sh/devops","https://docs.docker.com/","https://kubernetes.io/docs/"],
  "Celebration":["https://github.com/","https://dev.to/"],
};

export function buildPlan() {
  const p = {};
  RAW.forEach(([w, d, t, topic, sub, hrs]) => {
    if (!p[w]) p[w] = {};
    if (!p[w][d]) p[w][d] = [];
    p[w][d].push({ track: t, topic, sub, hrs, id: `${w}-${d}-${t}` });
  });
  return p;
}
export const PLAN = buildPlan();
export const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
